name = Sicurender
description = A simple 3 column layout for Sicurender.
;preview = preview.png
template = sicurender-layout

; Regions
regions[navigation]     = Navigation bar
regions[branding]       = Branding
regions[header]         = Header
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/sicurender/sicurender.layout.css
